### ISSUE TITLE
Powershell Gallery Version

### ISSUE THREAD

**Issue by ghost** [christaylorcodes/WebrootUnity#1]
Hi Chris, It look like the powershell gallery versision is not equal to the lastes commit e.g the New-WebrootConsoleGSMsite does not appear when installing from the gallery.

**Comment by ghost** [comment]
It looks like the New-WebrootConsoleGSMSite is the Get version.; Invoke-RestMethod -Method Get -Uri $url -ContentType "application/json" -Headers @{"Authorization" = "Bearer $($WebrootAuthToken.access_token)"}

Maybe this is it?

```
# New Site function
function New-WebrootConsoleGSMSite {
    #https://unityapi.webrootcloudav.com/Docs/APIDoc/Api/GET-api-console-gsm-gsmKey-sites-siteId
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$True)]
        [string]$GSMKey,
        [Parameter(Mandatory=$True)]
        [string]$SiteName,
        [Parameter(Mandatory=$True)]
        [int]$Seats,
        [Parameter(Mandatory=$True)]
        [string]$Comments,
        [ValidateSet("Annually","Quarterly","Monthly","Weekly")]
        [string]$BillingCycle,
        [string]$BillingDate,
        [switch]$GlobalPolicies,
        [switch]$GlobalOverrides,
        [string]$PolicyId,
        [Parameter(Mandatory=$True)]
        [string]$Emails
    )

    $url = "https://unityapi.webrootcloudav.com/service/api/console/gsm/$($GSMKey)/sites"

    $Body = @{SiteName=$SiteName;
                Seats=$Seats;
                Comments=$Comments;
                BillingCycle=$BillingCycle;
                BillingDate=$BillingDate;
                GlobalPolicies=$GlobalPolicies;
                GlobalOverrides=$GlobalOverrides;
                PolicyId=$PolicyId;
                Emails=$Emails;}
    
    $Body = $Body | ConvertTo-Json
    
if ($PSCmdlet.ShouldProcess($WebRequestArguments.URI, "Invoke-RestMethod, with body:`r`n$Body`r`n")) {
    Connect-WebrootUnity
    Write-Verbose $Body

    try{
        Invoke-RestMethod -Method Get -Uri $url -ContentType "application/json" -Body $Body -Headers @{"Authorization" = "Bearer $($WebrootAuthToken.access_token)"}
    }
    catch{
        Write-Error "Error: $($Error[0])"
    }
    }
}

```

**Comment by ghost** [comment]
Invoke-RestMethod -Method Get
must be POST offcourse

however, it doesn't work. For some reason I get a 401 error, acces denied due to invalid token.....

**Comment by ChrisTaylorRocks** [comment]
Seems as though I had duplicated the Get function in New-WebrootConsoleGSMSite. I have updated Git and PSGallery with the correct function. Please give it another try. Thanks for using the module and taking the time to submit the issue. c2f66f1f0068bf5c250bb7d5ea208eb4c5135baf

**Comment by christaylorcodes** [comment]
Looks like I had the Get function duplicated in New-WebrootConsoleGSMSite . I have corrected the issue and that function should now work. Please give it another try. Thanks for using the module and taking the time to submit an issue.
c2f66f1f0068bf5c250bb7d5ea208eb4c5135baf
