### ISSUE TITLE
Creating a new GSM Site

### ISSUE THREAD

**Issue by randemhero** [christaylorcodes/WebrootUnity#5]
Hello!

I am receiving the below when trying to create a new site in the GSM
```
PS C:\WINDOWS\system32> New-WebrootConsoleGSMSite
cmdlet New-WebrootConsoleGSMSite at command pipeline position 1
Supply values for the following parameters:
GSMKey: (Removed)
SiteName: Test
Seats: 10
Comments: TestSite
Emails: Testsite@test.com
New-WebrootConsoleGSMSite : Error: 
At line:1 char:1
+ New-WebrootConsoleGSMSite
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-WebrootConsoleGSMSite
```

Have tried correct email in the emails field, Left it empty and have also used a space but did not work

I have also successfully connected using Connect-WebrootUnity beforehand
Happy to perform more testing or gather more information when needed!

**Comment by christaylorcodes** [comment]
Thanks for reporting the issue.
Please update to 0.1.6.0 and give it another go.
